# Generated by Django 3.0 on 2020-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201123_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=5000)),
                ('discreption', models.CharField(max_length=5000)),
                ('link', models.CharField(max_length=5000)),
            ],
        ),
    ]
