# Generated by Django 3.0 on 2020-11-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursedisplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedisplay',
            old_name='discreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coursedisplay',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
